Implementing Multiple Linear Regression 

In [2]:
import matplotlib.pyplot as plt 
import numpy as np 
import math,copy 

In [5]:
x_train = np.array([[2104,5,1,45],[1416,3,2,40],[852,2,1,35]])
y_train = np.array([460,232,178])
print(x_train)
print(y_train)

[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
[460 232 178]


In [8]:
print(f"x_train shape: {x_train.shape}, x type : {type(x_train)}")
print(x_train)
print(f"y_train shape: {y_train.shape}, x type : {type(y_train)}")
print(y_train)

x_train shape: (3, 4), x type : <class 'numpy.ndarray'>
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y_train shape: (3,), x type : <class 'numpy.ndarray'>
[460 232 178]


In [10]:
b_init = 785.1811367994083
w_init = np.array([0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape} b_init shape: {type(b_init)}")

w_init shape: (4,) b_init shape: <class 'float'>


In [11]:
def predict_single_loop(x,w,b): #Sum of all dot products
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p += p_i
    p += b
    return p

In [13]:
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
f_wb = predict_single_loop(x_vec,w_init,b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [14]:
def predict(x,w,b): #same process as single_loop_predict
    p = np.dot(x,w) +  b
    return p 

In [15]:
x_vec = x_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
f_wb = predict(x_vec,w_init,b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.99999761940825


In [16]:
def compute_cost(x,y,w,b):
    m = x.shape[0]
    cost = 0.0
    for i in range(m): 
        f_wb_i = np.dot(x[i],w)+ b 
        cost = cost + (f_wb_i - y[i])**2
    cost = cost/(2*m)
    return cost


In [17]:
cost = compute_cost(x_train,y_train,w_init,b_init)
print(f"Cost at optimal w: {cost}")

Cost at optimal w: 1.5578904880036537e-12


In [19]:
def compute_gradient(x,y,w,b):
    m,n = x.shape #(number of examples, number of features)
    dj_dw = np.zeros((n,))
    dj_db = 0.
    for i in range(m):
        err = (np.dot(x[i],w) + b) - y[i] #denotation for the cost function
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * x[i,j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m
    return dj_db,dj_dw

In [21]:
tmp_dj_db,tmp_dj_dw = compute_gradient(x_train,y_train,w_init,b_init)
print(f"dj_db at initial w,b: {tmp_dj_db}")
print(f"dj_dw at initial w,b: {tmp_dj_dw}")

dj_db at initial w,b: -1.673925169143331e-06
dj_dw at initial w,b: [-2.72623581e-03 -6.27197272e-06 -2.21745580e-06 -6.92403399e-05]


In [ ]:
def gradient_descent(x,y,w_in,b_in,cost_function, gradient_function):
    