In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt

In [6]:
a = np.zeros(4)
print(f"np.zeros(4) : a = {a},a.shape = {a.shape}, a datatype = {a.dtype}")

a = np.zeros((4,))
print(f"np.zeros(4,) : a = {a},a.shape = {a.shape}, a datatype = {a.dtype}")

a = np.random.random_sample(4)
print(f"np.zeros(4,) : a = {a},a.shape = {a.shape}, a datatype = {a.dtype}")



np.zeros(4) : a = [0. 0. 0. 0.],a.shape = (4,), a datatype = float64
np.zeros(4,) : a = [0. 0. 0. 0.],a.shape = (4,), a datatype = float64
np.zeros(4,) : a = [0.89618023 0.32681677 0.81717589 0.692567  ],a.shape = (4,), a datatype = float64


In [10]:
a = np.arange(4.)
print(f"np.arange(4.) :a = {a}, shape = {a.shape}, datatype = {a.dtype}")

a = np.random.rand(4)
print(f"np.arange(4.) :a = {a}, shape = {a.shape}, datatype = {a.dtype}")


np.arange(4.) :a = [0. 1. 2. 3.], shape = (4,), datatype = float64
np.arange(4.) :a = [0.23334785 0.64695537 0.53431926 0.26322527], shape = (4,), datatype = float64


In [12]:
a = np.arange(10)
print(a)
print(f"a[2].shape: {a[2].shape} a[2] = {a[2]}")
print(f"a[-1] = {a[-1]}")



[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2] = 2
a[-1] = 9


In [25]:
a = np.linspace(1,10,10)
print(a)

c = a[2:7:1]
print(f"a[2:7:1] = {c}")

c = a[2:7:2]
print(f"a[2:7:2] = {c}")


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
a[2:7:1] = [3. 4. 5. 6. 7.]
a[2:7:2] = [3. 5. 7.]


In [30]:
a = np.linspace(1,4,4)
print(a)
b = -a
print(b)
b = np.sum(a)
print(b)
b = np.mean(a)
print(b)
b = a**2 
print(b)


[1. 2. 3. 4.]
[-1. -2. -3. -4.]
10.0
2.5
[ 1.  4.  9. 16.]


In [33]:
a = np.linspace(1,4,4)
b = np.linspace(1,4,4)
print(a)
print(b)
c = a+b 
print(c)
d = 5
e  = a*d
print(e)

[1. 2. 3. 4.]
[1. 2. 3. 4.]
[2. 4. 6. 8.]
[ 5. 10. 15. 20.]


In [34]:
#Dot product

def dot_product(a,b):
    x = 0
    for i in range(a.shape[0]):
        x = x + a[i]*b[i]
    return x 

a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
c =  dot_product(a,b)
print(c)


24


In [35]:
a = np.array([1,2,3,4])
b = np.array([-1,4,3,2])
c = np.dot(a,b)
print(c)

24
