In [7]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt 

In [15]:
df = pd.read_csv('C:\\Users\\rsurs\\OneDrive\\Documents\\Machine Learning\\Data_Preprocessing\\data.csv')
print(df)
print('\nmissing values')
df.isnull().sum()

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

missing values


Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [9]:
x  = df.iloc[:,:-1].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [10]:
y = df.iloc[:,-1].values 
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [13]:
#Addressing missing data
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [18]:
#One hot encoding is the process of encoding strings into a binary string
#One hot encoding the independent variable(country colmn) 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)
#France has vector 100, Spain has vector 001,Germany has vector 010

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [19]:
#Encoding the dependent variable (output colum)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(y) #Converts to no's and yes
print(y)


['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [26]:
#Exercise 
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
df = pd.read_csv('C:\\Users\\rsurs\\OneDrive\\Documents\\Machine Learning\\Data_Preprocessing\\titanic.csv')
df
#Output is survived rest all are inputs  

PassengerId  Survived  Pclass  \
0              2         1       1   
1              4         1       1   
2              7         0       1   
3             11         1       3   
4             12         1       1   
..           ...       ...     ...   
178          872         1       1   
179          873         0       1   
180          880         1       1   
181          888         1       1   
182          890         1       1   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                              McCarthy, Mr. Timothy J    male  54.0      0   
3                      Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                             Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
178   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
179                           Carlsson, Mr. Frans Olof    male  33.0      0   
180      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
181                       Graham, Miss. Margaret Edith  female  19.0      0   
182                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
0        0  PC 17599  71.2833          C85        C  
1        0    113803  53.1000         C123        S  
2        0     17463  51.8625          E46        S  
3        1   PP 9549  16.7000           G6        S  
4        0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
178      1     11751  52.5542          D35        S  
179      0       695   5.0000  B51 B53 B55        S  
180      1     11767  83.1583          C50        C  
181      0    112053  30.0000          B42        S  
182      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [27]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [39]:
#Encoding the dependent variables 
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
categorical_features = ['Sex','Pclass','Embarked']
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),categorical_features)],remainder='passthrough')
x = np.array(ct.fit_transform(df))
print(x)
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit_transform(y)
print(y)

[[1.0 0.0 1.0 ... 'PC 17599' 71.2833 'C85']
 [1.0 0.0 1.0 ... '113803' 53.1 'C123']
 [0.0 1.0 1.0 ... '17463' 51.8625 'E46']
 ...
 [1.0 0.0 1.0 ... '11767' 83.1583 'C50']
 [1.0 0.0 1.0 ... '112053' 30.0 'B42']
 [0.0 1.0 1.0 ... '111369' 30.0 'C148']]
[1 1 1 3 1 2 1 1 1 1 1 2 3 1 1 1 1 1 1 1 2 1 1 1 1 2 1 1 1 1 2 2 1 1 3 1 1
 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 2 1 2 1
 1 1 1 1 1 1 3 1 3 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1
 3 1 2 1 1 1 1 1 1 1 3 1 1 1 2 1 1 1 1 1 1 1 1 1 3 1 1 1 1 1 1 1 1 1 1]


In [40]:
import pandas as pd
import numpy as np
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

# Read the CSV file
df = pd.read_csv('C:\\Users\\rsurs\\OneDrive\\Documents\\Machine Learning\\Data_Preprocessing\\titanic.csv')

# Define categorical features and the target variable
categorical_features = ['Sex', 'Embarked', 'Pclass']

# Handle missing values in categorical columns
imputer = SimpleImputer(strategy='most_frequent')
df[categorical_features] = imputer.fit_transform(df[categorical_features])

# Apply ColumnTransformer with OneHotEncoder
ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), categorical_features)
    ], remainder='passthrough')

X = ct.fit_transform(df)

# Convert X to a numpy array (not necessary if you want to keep it as a DataFrame)
X = np.array(X)

# Encode the target variable using LabelEncoder
le = LabelEncoder()
y = le.fit_transform(df['Survived'])

print("Updated matrix of features: \n", X)
print("Updated dependent variable vector: \n", y)


Updated matrix of features: 
 [[1.0 0.0 1.0 ... 'PC 17599' 71.2833 'C85']
 [1.0 0.0 0.0 ... '113803' 53.1 'C123']
 [0.0 1.0 0.0 ... '17463' 51.8625 'E46']
 ...
 [1.0 0.0 1.0 ... '11767' 83.1583 'C50']
 [1.0 0.0 0.0 ... '112053' 30.0 'B42']
 [0.0 1.0 1.0 ... '111369' 30.0 'C148']]
Updated dependent variable vector: 
 [1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1]


In [41]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

df = pd.read_csv('C:\\Users\\rsurs\\OneDrive\\Documents\\Machine Learning\\Data_Preprocessing\\titanic.csv')
df

PassengerId  Survived  Pclass  \
0              2         1       1   
1              4         1       1   
2              7         0       1   
3             11         1       3   
4             12         1       1   
..           ...       ...     ...   
178          872         1       1   
179          873         0       1   
180          880         1       1   
181          888         1       1   
182          890         1       1   

                                                  Name     Sex   Age  SibSp  \
0    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
1         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
2                              McCarthy, Mr. Timothy J    male  54.0      0   
3                      Sandstrom, Miss. Marguerite Rut  female   4.0      1   
4                             Bonnell, Miss. Elizabeth  female  58.0      0   
..                                                 ...     ...   ...    ...   
178   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1   
179                           Carlsson, Mr. Frans Olof    male  33.0      0   
180      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0   
181                       Graham, Miss. Margaret Edith  female  19.0      0   
182                              Behr, Mr. Karl Howell    male  26.0      0   

     Parch    Ticket     Fare        Cabin Embarked  
0        0  PC 17599  71.2833          C85        C  
1        0    113803  53.1000         C123        S  
2        0     17463  51.8625          E46        S  
3        1   PP 9549  16.7000           G6        S  
4        0    113783  26.5500         C103        S  
..     ...       ...      ...          ...      ...  
178      1     11751  52.5542          D35        S  
179      0       695   5.0000  B51 B53 B55        S  
180      1     11767  83.1583          C50        C  
181      0    112053  30.0000          B42        S  
182      0    111369  30.0000         C148        C  

[183 rows x 12 columns]

In [56]:
categorical_features = ['Sex','Embarked','Pclass']
imputer = SimpleImputer(strategy='most_frequent')
df[categorical_features] = imputer.fit_transform(df[categorical_features])
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),categorical_features)],remainder='passthrough')
x = np.array(ct.fit_transform(df))
print(x)
le = LabelEncoder()
y = le.fit_transform(df['Survived'])
print(y)


[[1.0 0.0 1.0 ... 'PC 17599' 71.2833 'C85']
 [1.0 0.0 0.0 ... '113803' 53.1 'C123']
 [0.0 1.0 0.0 ... '17463' 51.8625 'E46']
 ...
 [1.0 0.0 1.0 ... '11767' 83.1583 'C50']
 [1.0 0.0 0.0 ... '112053' 30.0 'B42']
 [0.0 1.0 1.0 ... '111369' 30.0 'C148']]
[1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1]
