In [10]:
#Continuing ex3
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
from sklearn.compose import ColumnTransformer

df = pd.read_csv('titanic.csv')
df
categorical_transformers = ['Sex','Pclass','Embarked']
imputer = SimpleImputer(strategy='most_frequent')
df[categorical_transformers] = imputer.fit_transform(df[categorical_transformers]) 
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),categorical_transformers)],remainder='passthrough')
x = ct.fit_transform(df)
x = np.array(x)
print("The matrix of updated features\n",x)

le = LabelEncoder()
y = le.fit_transform(df['Survived'])
print('Dependent variable\n',y)

The matrix of updated features
 [[1.0 0.0 1.0 ... 'PC 17599' 71.2833 'C85']
 [1.0 0.0 1.0 ... '113803' 53.1 'C123']
 [0.0 1.0 1.0 ... '17463' 51.8625 'E46']
 ...
 [1.0 0.0 1.0 ... '11767' 83.1583 'C50']
 [1.0 0.0 1.0 ... '112053' 30.0 'B42']
 [0.0 1.0 1.0 ... '111369' 30.0 'C148']]
Dependent variable
 [1 1 0 1 1 1 1 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 1 1
 1 1 1 0 1 0 0 1 0 0 1 1 0 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 1
 1 1 1 0 1 1 1 1 1 1 0 1 0 1 1 0 1 0 1 0 1 1 1 0 0 1 0 1 0 1 0 1 1 1 0 1 1
 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 0 0 1 1 1 1 0 0 1 1 1 1 1
 0 1 1 1 1 1 0 1 0 0 1 1 1 1 0 1 1 0 0 1 1 0 1 1 1 1 1 1 1 0 1 0 1 1 1]


In [21]:
import numpy as np 
import pandas as pd 
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder,LabelEncoder

df = pd.read_csv('data.csv')

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

imputer = SimpleImputer(missing_values=np.nan,strategy='mean')
x[:,1:3] = imputer.fit_transform(x[:,1:3])

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

le = LabelEncoder()
y= le.fit_transform(y)
print(y)



[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into training set and test set 

In [23]:
from sklearn.model_selection import train_test_split
#X-train:One hot encoded variable(cpuntries,ages,salaries)
#X-test:Matrix of features of test set
#Y-train:Dependent variable(purchases) in train set
#Y-test:purchases in test set
#Split should be 80% training set ,20% test set
x_train,x_test,y_train,y_test =  train_test_split(x,y,test_size=0.2,random_state=1)

In [24]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [25]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [26]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [27]:
print(y_test)

[0 1]
